import { GetServerSideProps } from "next";
import Head from "next/head";
import { fetchArticles, fetchCategories } from "../utils";
import { AxiosResponse } from "axios";
import { IArticle, ICategory, ICollectionResponse } from "../types";
import Tabs from "../components/Tabs";
import ArticleList from "../components/ArticleList";

interface IPropTypes {
  categories: {
    items: ICategory[];
  };
  articles: {
    items: IArticle[];
  };
}

const Home = ({ categories, articles }: IPropTypes) => {
  return (
    <>
      <Head>
        <title>Next-Strapi Project </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Tabs categories={categories.items} />
      <ArticleList articles={articles.items} />
    </>
  );
};
export const getServerSideProps: GetServerSideProps = async () => {
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> =
    await fetchArticles();

  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  return {
    props: {
      categories: {
        items: categories.data,
      },
      articles: {
        items: articles.data,
        pagination: articles.meta.pagination,
      },
    },
  };
};

export default Home;
