import { GetServerSideProps } from "next";
import Head from "next/head";
import { fetchCategories } from "../utils";
import { AxiosResponse } from "axios";
import { ICategory, ICollectionResponse } from "../types";
import Tabs from "../components/Tabs";

interface IPropTypes {
  categories: {
    items: ICategory[];
  };
}

const Home = ({ categories }: IPropTypes) => {
  return (
    <>
      <Head>
        <title>Next-Strapi Project </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Tabs categories={categories.items} />
    </>
  );
};
export const getServerSideProps: GetServerSideProps = async () => {
  // const {data:articles}:AxiosResponse<ICollectionResponse<IArticle>> = await fetchCategories();

  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  return {
    props: {
      categories: {
        items: categories.data,
      },
    },
  };
};

export default Home;
